/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaluRouteImport } from './routes/calu'
import { Route as ComecarRouteImport } from './routes/comecar'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaluRoute = CaluRouteImport.update({
  id: '/calu',
  path: '/calu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calu': typeof CaluRoute
  '/comecar': typeof ComecarRoute
  '/diario': typeof DiarioRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/progresso': typeof ProgressoRoute
  '/registrar': typeof RegistrarRoute
  '/termos': typeof TermosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calu': typeof CaluRoute
  '/comecar': typeof ComecarRoute
  '/diario': typeof DiarioRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/progresso': typeof ProgressoRoute
  '/registrar': typeof RegistrarRoute
  '/termos': typeof TermosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calu': typeof CaluRoute
  '/comecar': typeof ComecarRoute
  '/diario': typeof DiarioRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/progresso': typeof ProgressoRoute
  '/registrar': typeof RegistrarRoute
  '/termos': typeof TermosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calu'
    | '/comecar'
    | '/diario'
    | '/login'
    | '/perfil'
    | '/privacidade'
    | '/progresso'
    | '/registrar'
    | '/termos'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calu'
    | '/comecar'
    | '/diario'
    | '/login'
    | '/perfil'
    | '/privacidade'
    | '/progresso'
    | '/registrar'
    | '/termos'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/calu'
    | '/comecar'
    | '/diario'
    | '/login'
    | '/perfil'
    | '/privacidade'
    | '/progresso'
    | '/registrar'
    | '/termos'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaluRoute: typeof CaluRoute
  ComecarRoute: typeof ComecarRoute
  DiarioRoute: typeof DiarioRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProgressoRoute: typeof ProgressoRoute
  RegistrarRoute: typeof RegistrarRoute
  TermosRoute: typeof TermosRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calu': {
      id: '/calu'
      path: '/calu'
      fullPath: '/calu'
      preLoaderRoute: typeof CaluRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaluRoute: CaluRoute,
  ComecarRoute: ComecarRoute,
  DiarioRoute: DiarioRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProgressoRoute: ProgressoRoute,
  RegistrarRoute: RegistrarRoute,
  TermosRoute: TermosRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
